-- 코드를 입력하세요
WITH CC AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE = "SUV" OR CAR_TYPE = "세단"
)
, CH AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > "2022-11-01" AND START_DATE < "2022-11-30"
    )
)
, CD AS (
    SELECT CAR_TYPE, 1-DISCOUNT_RATE/100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE = "30일 이상"
)
SELECT CC.CAR_ID, CC.CAR_TYPE, ROUND(CC.DAILY_FEE*CD.DISCOUNT_RATE*30) AS FEE
FROM CC
INNER JOIN CH
ON CC.CAR_ID = CH.CAR_ID
INNER JOIN CD
ON CC.CAR_TYPE = CD.CAR_TYPE
WHERE ROUND(CC.DAILY_FEE*CD.DISCOUNT_RATE*30) BETWEEN 500000 AND 1999999
GROUP BY CC.CAR_ID
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC