SELECT ID,
(
    CASE
    WHEN RANKING / (SELECT COUNT(ID) FROM ECOLI_DATA) * 100 <= 25 THEN 'CRITICAL'
    WHEN RANKING / (SELECT COUNT(ID) FROM ECOLI_DATA) * 100 <= 50 THEN 'HIGH'
    WHEN RANKING / (SELECT COUNT(ID) FROM ECOLI_DATA) * 100 <= 75 THEN 'MEDIUM'
    ELSE 'LOW'
    END
) AS COLONY_NAME
FROM (
    SELECT *, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKING
    FROM ECOLI_DATA
) AS A
ORDER BY ID