-- 코드를 입력하세요
# 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD A, USED_GOODS_REPLY B
where A.BOARD_ID = B.BOARD_ID AND MONTH(A.CREATED_DATE)=10
ORDER BY B.CREATED_DATE, A.TITLE;