WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN TIME AS T
ON HOUR(AO.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR
