SELECT GU.USER_ID, GU.NICKNAME, SUM(GB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS GB, USED_GOODS_USER AS GU
WHERE GB.WRITER_ID = GU.USER_ID AND GB.STATUS = "DONE"
GROUP BY GU.USER_ID
HAVING SUM(GB.PRICE) >= 700000
ORDER BY TOTAL_SALES